# Generated by Django 5.2.6 on 2025-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
