# Generated by Django 5.2.6 on 2025-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_alter_department_slug_alter_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
