# Generated by Django 5.2.6 on 2025-10-09 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0003_alter_department_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cr_profile_pictures/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('st_id', models.CharField(max_length=50, unique=True)),
                ('batch', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dalete_at', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profile', to='cr.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profile', to='cr.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
