# Generated by Django 5.2.6 on 2025-10-09 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0004_crprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='crprofile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='crprofile',
            old_name='dalete_at',
            new_name='daleted_at',
        ),
        migrations.RenameField(
            model_name='crprofile',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dalete_at',
            new_name='daleted_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='dalete_at',
            new_name='daleted_at',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cr_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cr.crprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
