# Generated by Django 5.2.6 on 2025-10-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0007_alter_review_cr_profile_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
