# Generated by Django 5.2.6 on 2025-10-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0008_alter_crprofile_slug_alter_department_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crprofile',
            old_name='daleted_at',
            new_name='deleted_at',
        ),
    ]
