# Generated by Django 5.2.6 on 2025-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0009_rename_daleted_at_crprofile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1),
            preserve_default=False,
        ),
    ]
