# Generated by Django 5.2.6 on 2025-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0011_alter_crprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crprofile',
            name='dept_batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crprofile',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='crprofile',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='crprofile',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
    ]
