# Generated by Django 5.2.6 on 2025-10-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0012_crprofile_dept_batch_crprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
