# Generated by Django 5.2.6 on 2025-10-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0013_crprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='crprofile',
            name='cr_status',
            field=models.CharField(choices=[('Present', 'Present CR'), ('Former', 'Former CR')], default='Present', max_length=20),
        ),
    ]
