# Generated by Django 5.2.6 on 2025-10-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0014_crprofile_cr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
