# Generated by Django 5.2.6 on 2025-10-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0016_alter_review_options_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
    ]
