# Generated by Django 5.2.6 on 2025-10-28 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0017_remove_department_university'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
