# Generated by Django 5.2.6 on 2025-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0018_review_is_approved_review_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
