# Generated by Django 5.2.6 on 2025-11-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0019_alter_crprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
