# Generated by Django 5.2.6 on 2025-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0020_alter_crprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
