# Generated by Django 5.2.6 on 2025-11-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0023_alter_department_code_alter_department_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='daleted_at',
            new_name='deleted_at',
        ),
    ]
