# Generated by Django 5.2.6 on 2025-11-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0024_rename_daleted_at_department_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='daleted_at',
            new_name='deleted_at',
        ),
    ]
