# Generated by Django 5.2.6 on 2025-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default_profile.png', null=True, upload_to='user_profile_picture_path'),
        ),
    ]
