# Generated by Django 5.2.6 on 2025-10-10 19:05

import django.db.models.deletion
import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_alter_review_user'),
        ('userprofile', '0003_alter_user_batch_alter_user_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instqgram_url',
            new_name='instagram_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='cr.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university', to='cr.university'),
        ),
    ]
