# Generated by Django 5.2.6 on 2025-10-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_user_gender_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
