# Generated by Django 5.2.6 on 2025-10-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0010_crprofile_gender'),
        ('userprofile', '0007_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('cr_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='cr.crprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_crs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cr_profile')},
            },
        ),
    ]
