# Generated by Django 5.2.6 on 2025-11-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_user_department_alter_user_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
