# Generated by Django 5.2.6 on 2025-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teck_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Developer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='developer_profile_pictures/')),
                ('name', models.CharField(max_length=100)),
                ('degisnation', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('years_of_experience', models.IntegerField()),
                ('projects_built', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('tack_stack', models.ManyToManyField(to='footer.teck_stack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
