# Generated by Django 5.2.6 on 2025-10-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_teck_stack_developer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer_profile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='degisnation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='developer_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='projects_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='tack_stack',
            field=models.ManyToManyField(blank=True, null=True, related_name='developer_profiles', to='footer.teck_stack'),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
