# Generated by Django 5.2.6 on 2025-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_alter_developer_profile_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teck_stack',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='developer_profile',
            name='tack_stack',
            field=models.ManyToManyField(blank=True, related_name='developer_profiles', to='footer.teck_stack'),
        ),
    ]
