# Generated by Django 5.2.6 on 2025-11-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_alter_teck_stack_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Developer_Profile',
        ),
        migrations.DeleteModel(
            name='Teck_Stack',
        ),
    ]
